[package]
name = "gpapi-cli"
version = "0.1.0"
authors = ["David Weinstein <dweinst@insitusec.com>"]

[dependencies]
clap = {version = "2", features = ["yaml"]}
serde_json = "1"

[dependencies.gpapi]
path = "../gpapi"
